# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCodeProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.TextField()),
                ('code_content', models.TextField()),
                ('lang', models.TextField()),
                ('code_input', models.TextField()),
                ('compile_status', models.TextField()),
                ('run_status_status', models.TextField()),
                ('run_status_time', models.TextField()),
                ('run_status_memory', models.TextField()),
                ('run_status_output', models.TextField()),
                ('run_status_stderr', models.TextField()),
            ],
        ),
    ]
